sudo: required
dist: trusty
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libgtk-3-dev
      - libsoup2.4-dev
      - libxtst-dev
      - at-spi2-core

env:
  - RUST_BACKTRACE=1

rust:
  - nightly
  #- beta
  #- stable

before_install:
  - sudo add-apt-repository ppa:webkit-team/ppa -y
  - sudo apt-get update
  - sudo apt-get install libwebkit2gtk-4.0-dev -y

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - openbox # needs a window manager for the tests (to get focus to work)

script:
  - cargo build
  - cargo test
  - cargo test --examples
  - cargo build --manifest-path examples/buttons-attribute/Cargo.toml
  #- cargo build --manifest-path examples/http/Cargo.toml
  #- cargo build --manifest-path examples/async/Cargo.toml
  - cargo build --manifest-path examples/webkit-test/Cargo.toml
  - cargo build --manifest-path examples/buttons-derive/Cargo.toml

matrix:
  allow_failures:
    - rust: stable
    - rust: beta
