environment:
  matrix:
    - RUST: nightly
      BITS: 32
    - RUST: nightly
      BITS: 64

install:
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/channel-rust-nightly"
  - ps: $env:RUST_VERSION = Get-Content channel-rust-nightly | select -first 1 | %{$_.split('-')[1]}
  - if NOT "%RUST%" == "nightly" set RUST_VERSION=%RUST%
  - SET RUST_URL=https://static.rust-lang.org/dist/rust-%RUST_VERSION%-%ARCH%-pc-windows-gnu.exe
  - SET PATH=C:\Rust\bin;C:\msys64\mingw%BITS%\bin;%PATH%;C:\msys64\usr\bin
  - ps: Start-FileDownload $Env:RUST_URL -FileName rust-dist.exe
  - rust-dist.exe /VERYSILENT /NORESTART /COMPONENTS="Rustc,Gcc,Cargo,Std" /DIR="C:\Rust"
  - rustc -V
  - cargo -V
  - pacman --noconfirm -S mingw-w64-%ARCH%-gtk3

build_script:
  - mkdir .cargo
  - echo paths = ["."] > .cargo\config
  - cargo test

test: false
