[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["asynchronous", "gui"]
description = "Asynchronous, GTK+-based, GUI library, inspired by Elm, written in Rust"
documentation = "https://docs.rs/relm/"
license = "MIT"
name = "relm"
repository = "https://github.com/antoyo/relm"
version = "0.9.6"

[badges]

[badges.appveyor]
branch = "master"
repository = "antoyo/relm"

[badges.travis-ci]
branch = "master"
repository = "antoyo/relm"

[dependencies]
glib = "^0.1.2"
glib-itc = "^0.1.1"
glib-sys = "^0.3.4"
gobject-sys = "^0.3.3"
gtk = "^0.1.1"
gtk-sys = "^0.3.3"
libc = "^0.2.22"

[dependencies.futures]
branch = "spawn-trait"
git = "https://github.com/alexcrichton/futures-rs"

[dependencies.futures-glib]
git = "https://github.com/antoyo/futures-glib-rs"

[dependencies.relm-core]
path = "relm-core"
version = "^0.1.1"

[dependencies.relm-state]
path = "relm-state"
version = "^0.1.0"

[dev-dependencies]
base64 = "^0.4.0"
blake2 = "^0.4.0"
byteorder = "^1.0.0"
chrono = "^0.3.0"
rand = "^0.3.15"
simplelog = "^0.4.2"
tokio-core = "^0.1.4"
tokio-proto = "^0.1.0"
tokio-service = "^0.1.0"
twist = "^0.5.0"
url = "^1.4.0"

[dev-dependencies.relm-attributes]
path = "relm-attributes"
version = "^0.9.0"

[dev-dependencies.relm-derive]
path = "relm-derive"
version = "^0.9.0"

[dev-dependencies.relm-test]
path = "relm-test"
version = "^0.1.0"

[features]
nightly = []
use_impl_trait = []

[metadata]

[metadata.release]

[[metadata.release.pre-release-replacements]]
file = "README.adoc"
replace = "relm = \"{{version}}\""
search = "relm = \"[a-z0-9^\\.-]+\""

[[metadata.release.pre-release-replacements]]
file = "src/lib.rs"
replace = "relm = \"{{version}}\""
search = "relm = \"[a-z0-9^\\.-]+\""

[[metadata.release.pre-release-replacements]]
file = "examples/buttons-derive/Cargo.toml"
replace = "relm = \"{{version}}\""
search = "relm = \"[a-z0-9^\\.-]+\""

[replace]

[replace."futures:0.1.13"]
branch = "spawn-trait"
git = "https://github.com/alexcrichton/futures-rs"
