[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["asynchronous", "gui"]
description = "Asynchronous, GTK+-based, GUI library, inspired by Elm, written in Rust"
documentation = "https://docs.rs/relm/"
license = "MIT"
name = "relm"
readme = "README.adoc"
repository = "https://github.com/antoyo/relm"
version = "0.14.4"

[badges.appveyor]
branch = "master"
repository = "antoyo/relm"

[badges.travis-ci]
branch = "master"
repository = "antoyo/relm"

[dependencies]
glib = "^0.5.0"
glib-sys = "^0.6.0"
gobject-sys = "^0.6.0"
gtk = "^0.4.0"
gtk-sys = "^0.6.0"
libc = "^0.2.22"

[dependencies.relm-core]
path = "relm-core"
version = "^0.14.0"

[dependencies.relm-state]
path = "relm-state"
version = "^0.14.0"

[dev-dependencies]
chrono = "0.4"
gdk = "^0.8.0"

[dev-dependencies.gio]
version = "^0.4.0"

[dev-dependencies.relm-attributes]
path = "relm-attributes"
version = "^0.14.0"

[dev-dependencies.relm-derive]
path = "relm-derive"
version = "^0.14.0"

[dev-dependencies.relm-test]
path = "relm-test"
version = "^0.14.0"

[features]
default = ["unstable"]
nightly = []
unstable = []

[[metadata.release.pre-release-replacements]]
file = "README.adoc"
replace = "relm = \"{{version}}\""
search = "relm = \"[a-z0-9^\\.-]+\""
[[metadata.release.pre-release-replacements]]
file = "src/lib.rs"
replace = "relm = \"{{version}}\""
search = "relm = \"[a-z0-9^\\.-]+\""
