[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "async"
version = "0.1.0"

[dependencies]
gtk = "^0.6.0"
gtk-sys = "^0.8.0"

[dependencies.gio]
features = ["v2_50"]
version = "^0.6.0"

[dependencies.relm]
path = "../.."

[dependencies.relm-derive]
path = "../../relm-derive"
