[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
description = "Non UI part of relm"
license = "MIT"
name = "relm-state"
repository = "https://github.com/antoyo/relm"
version = "0.15.2"

[dependencies]
log = "0.4"

[dependencies.relm-core]
path = "../relm-core"
version = "^0.15.0"
