[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "buttons-derive"
version = "0.1.0"

[dependencies]
gtk = "^0.5.0"
relm = { path = "../..", default-features = false }
relm-derive = { path = "../../relm-derive" }
