[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["development-tools::testing", "gui"]
description = "Testing library for relm"
documentation = "https://docs.rs/relm-test/"
license = "MIT"
name = "relm-test"
repository = "https://github.com/antoyo/relm"
version = "0.19.0"
edition = "2018"

[dependencies]
gtk-test = "^0.5"

[dependencies.relm]
path = ".."
version = "^0.18.0"
